language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8"
      env: TOXENV=py38
      dist: bionic
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: bionic
    - python: "pypy2"
      env: TOXENV=pypy2
    - python: "pypy3"
      env: TOXENV=pypy3
    # os checks
    - os: osx
      env: TOXENV=py27
      language: minimal
    - os: osx
      env: TOXENV=py37
      language: minimal
      osx_image: xcode10.2 # python 3.7.3
    - os: windows
      env: TOXENV=py27
      language: sh
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - os: windows
      env: TOXENV=py38
      language: sh
      before_install:
        - choco install python3 --params "/InstallDir:C:\Python" --version=3.8.0
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
    # other
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=pylint

install:
  - pip install --upgrade tox

script:
  - tox

notifications:
  email: false
